# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deviceRegistration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64\x65viceRegistration.proto\x12\x12\x44\x65viceRegistration\"u\n\x19\x44\x65viceRegistrationRequest\x12\x16\n\x0e\x64\x65vice_mac_add\x18\x01 \x01(\t\x12\x18\n\x10\x64\x65vice_unique_id\x18\x02 \x01(\t\x12\x12\n\nfw_version\x18\x03 \x01(\t\x12\x12\n\nos_version\x18\x04 \x01(\t\"\x95\x01\n\x1a\x44\x65viceRegistrationResponse\x12\x36\n\x06status\x18\x01 \x01(\x0e\x32&.DeviceRegistration.RegistrationStatus\x12\x12\n\nserver_url\x18\x02 \x01(\t\x12\x18\n\x10unique_system_id\x18\x03 \x01(\t\x12\x11\n\terror_msg\x18\x04 \x01(\t*M\n\x12RegistrationStatus\x12\x12\n\x0eREG_SUCCESSFUL\x10\x00\x12\x14\n\x10REG_UNSUCCESSFUL\x10\x01\x12\r\n\tREG_ERROR\x10\x02\x32\x87\x01\n\x12\x44\x65viceRegistration\x12q\n\x0eRegisterDevice\x12-.DeviceRegistration.DeviceRegistrationRequest\x1a..DeviceRegistration.DeviceRegistrationResponse\"\x00\x42\x14Z\x12\x64igitalSignage/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deviceRegistration_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\022digitalSignage/api'
  _globals['_REGISTRATIONSTATUS']._serialized_start=319
  _globals['_REGISTRATIONSTATUS']._serialized_end=396
  _globals['_DEVICEREGISTRATIONREQUEST']._serialized_start=48
  _globals['_DEVICEREGISTRATIONREQUEST']._serialized_end=165
  _globals['_DEVICEREGISTRATIONRESPONSE']._serialized_start=168
  _globals['_DEVICEREGISTRATIONRESPONSE']._serialized_end=317
  _globals['_DEVICEREGISTRATION']._serialized_start=399
  _globals['_DEVICEREGISTRATION']._serialized_end=534
# @@protoc_insertion_point(module_scope)
