# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import deviceRegistration_pb2 as deviceRegistration__pb2


class DeviceRegistrationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDevice = channel.unary_unary(
                '/DeviceRegistration.DeviceRegistration/RegisterDevice',
                request_serializer=deviceRegistration__pb2.DeviceRegistrationRequest.SerializeToString,
                response_deserializer=deviceRegistration__pb2.DeviceRegistrationResponse.FromString,
                )


class DeviceRegistrationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceRegistrationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDevice,
                    request_deserializer=deviceRegistration__pb2.DeviceRegistrationRequest.FromString,
                    response_serializer=deviceRegistration__pb2.DeviceRegistrationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DeviceRegistration.DeviceRegistration', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeviceRegistration(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DeviceRegistration.DeviceRegistration/RegisterDevice',
            deviceRegistration__pb2.DeviceRegistrationRequest.SerializeToString,
            deviceRegistration__pb2.DeviceRegistrationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
