openapi: 3.0.0
info:
  title: dss
  version: 1.0.0
servers:
  - url: https://register.dss.com:4000
  - url: https://device.dss.com:4001
tags:
  - name: device
  - name: web
paths:
  /device/registerDevice:
    post:
      tags:
        - device
      summary: https://register.dss.com:4000/device/registerDevice
      description: >-
        Register device with backend server by providing mac address and ip
        address.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                Mac: b8:27:eb:e8:40:6f
                IpAddr: 192.168.165.15
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /device/statusUpdate:
    post:
      tags:
        - device
      summary: https://device.dss.com:4001/device/statusUpdate
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\r\n   
                \"RegistrationId\":\"0b595f59-b246-402c-9079-e1fa1a5ab8be\",\r\n   
                \"ScheduleAllocId\":\"36414f0d-da7d-493e-8efd-358690ee8568\",\r\n   
                \"ContentAllocId\":\"23177bfe-c4df-4fca-8ab1-2ea19ea2bb78\",\r\n   
                \"App_Version\":\"1.1\",\r\n    \"Os_Version\":\"1.1\",\r\n   
                \"IpAddr\":\"127.01.01.01\"\r\n}"
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /device/getContent:
    get:
      tags:
        - device
      summary: https://device.dss.com:4001/device/getContent
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /device/getPlaySchedule:
    get:
      tags:
        - device
      summary: https://device.dss.com:4001/device/getPlaySchedule
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /web/login:
    post:
      tags:
        - web
      summary: https://device.dss.com:4001/web/login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ''
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /web/addLocation:
    post:
      tags:
        - web
      summary: https://device.dss.com:4001/web/addLocation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                Country: Germany
                City: Frankfurt
                Building: Fra-Uas
                Area: B1-F1-W2
                Mac: b8:27:eb:bd:15:3a
                StartDate: 30-09-2023
                EndDate: 30-12-2023
                StartTime: '11:00'
                EndTime: '15:00'
                ContentInfoId: 404af461-9490-4feb-b1f2-603d47735a85
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /web/addDevice:
    post:
      tags:
        - web
      summary: https://device.dss.com:4001/web/addDevice
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\r\n    \"Mac\":\"ab:ac:ad:ae:af\", \r\n   
                \"Location\":\"Germany\"\r\n}"
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /web/addContent:
    post:
      tags:
        - web
      summary: https://device.dss.com:4001/web/addContent
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                File:
                  type: string
                  format: binary
                FileName:
                  type: string
                  example: TestFile5
                Description:
                  type: string
                  example: This is a test file
                FileSize:
                  type: integer
                  example: '25132345'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /web/removeContent:
    post:
      tags:
        - web
      summary: https://device.dss.com:4001/web/removeContent
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                ContentId: abc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /web/removeLocation:
    post:
      tags:
        - web
      summary: https://device.dss.com:4001/web/removeLocation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                DeviceId: ab:ac:ad:ae:af
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /web/updateAllocContent:
    post:
      tags:
        - web
      summary: https://device.dss.com:4001/web/updateAllocContent
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                Mac: b8:27:eb:e8:40:6f
                ContentInfoId: 1cd14b4d-dca5-4646-8511-e8d10419c02d
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /web/updateAllocSchedule:
    post:
      tags:
        - web
      summary: https://device.dss.com:4001/web/updateAllocSchedule
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                Mac: b8:27:eb:e8:40:6f
                StartDate: 13-10-2023
                EndDate: 01-01-2024
                StartTime: '07:00'
                EndTime: '19:00'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /web/getDeviceInfoList:
    get:
      tags:
        - web
      summary: https://device.dss.com:4001/web/getDeviceInfoList
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /web/getContentList:
    get:
      tags:
        - web
      summary: https://device.dss.com:4001/web/getContentList
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /web/getCountryList:
    get:
      tags:
        - web
      summary: https://device.dss.com:4001/web/getCountryList
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /web/getCityList:
    get:
      tags:
        - web
      summary: https://device.dss.com:4001/web/getCityList
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /web/getBuildingList:
    get:
      tags:
        - web
      summary: https://device.dss.com:4001/web/getBuildingList
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /web/getAreaList:
    get:
      tags:
        - web
      summary: https://device.dss.com:4001/web/getAreaList
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /web/getEventStream:
    get:
      tags:
        - web
      summary: https://device.dss.com:4001/web/getEventStream
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
